version: "3"
services:
  frontend:
    image: chantifa/blueplanet-frontend:3.0.0
    container_name: frontend
    build: ./frontend
    volumes:
      -  blueplanet-volume:/frontend/
      - ./frontend:/frontend/
    ports:
      - 8080:8080
    working_dir: /frontend/
    networks:
      - mynetwork
    stdin_open: true
    restart: always
  backend:
    image: chantifa/blueplanet-backend:2.0.0
    container_name: backend
    build: ./backend
    volumes:
      - blueplanet-volume:/backend/
      - ./backend:/backend
    ports:
      - 4000:4000
    networks:
      - mynetwork
    environment:
      DB_HOST_NAME: storage
      SPRING_PROFILES_ACTIVE: container
    depends_on:
      - storage
    restart: always

  storage:
    image: chantifa/blueplanet-storage:2.0.0
    container_name: database
    build: ./backend/database
    volumes:
      - blueplanet-volume:/var/lib/postgresql/data
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blueplanet
    ports:
      - 5432:5432
    restart: always
networks:
  mynetwork:
volumes:
  blueplanet-volume: